### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by gitnnm** [SealinGp/ytb-downloader#1]
1. By get request I receive information about the video, but for some reason the video and audio are sent separately, I don’t understand why this is?
2. I still don’t understand how to create a post request for downloading videos?

**Comment by SealinGp** [comment]
this repo is not finished yet, and it's not a library, maybe you want to use golang library to download video? you should refer this repo https://github.com/kkdai/youtube to fulfill your requirement.

**Comment by SealinGp** [comment]
> 1. By get request I receive information about the video, but for some reason the video and audio are sent separately, I don’t understand why this is?
> 2. I still don’t understand how to create a post request for downloading videos?
@gitnnm 
1. the youtube video info contains muti encoding lists(seperate by different quality) about video or audio, you should use one of them.
<img width="1955" alt="image" src="https://github.com/SealinGp/ytb-downloader/assets/32982627/76ee363c-3e93-46d3-a675-ae5409f63b4e">

2. this repo is not a library, maybe you want to use golang library to download video? you should refer this repo https://github.com/kkdai/youtube to fulfill your requirement. 
also docker images has been published , you're welcome to use: https://hub.docker.com/repository/docker/sealingp/ytb-downloader/general

**Comment by gitnnm** [comment]
Interesting. I launched the application using your scripts, but I do not have such an interface. Only APIs for receiving information in json format work

**Comment by gitnnm** [comment]
> > 1. By get request I receive information about the video, but for some reason the video and audio are sent separately, I don’t understand why this is?
> > 2. I still don’t understand how to create a post request for downloading videos?
> >    @gitnnm
> 
> 1. the youtube video info contains muti encoding lists(seperate by different quality) about video or audio, you should use one of them.
> 
> <img alt="image" width="1955" src="https://private-user-images.githubusercontent.com/32982627/342297748-76ee363c-3e93-46d3-a675-ae5409f63b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY2NTYsIm5iZiI6MTcxOTY2NjM1NiwicGF0aCI6Ii8zMjk4MjYyNy8zNDIyOTc3NDgtNzZlZTM2M2MtM2U5My00NmQzLWE2NzUtYWU1NDA5ZjYzYjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMDU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTNiMGRiNzUzZDRjMWRlODI4NDg4N2JkZjA4OTA4YjM4NGNhMzBkNjAwMjVlZmE0NjIyYTMxNGQ0NWM1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkWyBzAL-1gsLDW1mWUeNCCvpG0-ZdIHRt-7dEumH4U">
> 2. this repo is not a library, maybe you want to use golang library to download video? you should refer this repo https://github.com/kkdai/youtube to fulfill your requirement.
>    also docker images has been published , you're welcome to use: https://hub.docker.com/repository/docker/sealingp/ytb-downloader/general
Interesting. I launched the application using your scripts, but I do not have such an interface. Only APIs for receiving information in json format work

**Comment by gitnnm** [comment]
go library on docker

![yt](https://github.com/SealinGp/ytb-downloader/assets/95910234/822d4cc9-a5a4-47de-abe4-c2f70558b14a)

**Comment by SealinGp** [comment]
> go library on docker

@gitnnm  pull the latest image and rebuild the container, then try it again

**Comment by SealinGp** [comment]
closed the issue, if you have any question, open a new one.
